### ISSUE TITLE
Add Basic CRUD Endpoints

### ISSUE THREAD

**Issue by benmccormick** [fif4evr/personally-api#2]
Each object should have its own set of HTTP Endpoints

The total set should probably look like this:

- [x] `GET /employees # get all employees`
- [x] `GET /employees/:id  # get employees with id :id`
- [x] `POST /employees  # Add new employee`
- [x] `PUT /employees/:id #update a specific employee`
- [x] `DELETE /employees/:id #remove a specific employeee`

- [x] `GET /companies # get all companies`
- [x] `GET /companies/:id # get company with id :id`
- [x] `POST /companies  # Add new company`
- [x] `PUT /companies/:id # update a specific company`
- [x] `DELETE /companies/:id #remove a specific company`

- [x] `GET /departments # get all departments`
- [x] `GET /departments/:id # get departments with id :id`
- [x] `POST /departments  # Add new department`
- [x] `PUT /departments/:id # update a specific department`
- [x] `DELETE /departments/:id #remove a specific departments`

- [x] `GET /personality_types # get all personality types`
- [x] `GET /personality_types/:signature #get personality type with signature`

- [x] `GET /letters # get all letters`
- [x] `GET /letters/:letter #get specific letter`

We can work out later exactly what JSON each GET should return, but for right now we just want to be able to do all of these.

**Comment by fif4evr** [comment]
#DONE GET /employees # get all employees
#DONE GET /employees/:id  # get employees with id :id
#DONE POST /employees  # Add new employee
#DONE PUT /employees/:id #update a specific employee
#DONE DELETE /employees/:id #remove a specific employeee

#DONE GET /companies # get all companies
#DONE GET /companies/:id # get company with id :id
#DONE POST /companies  # Add new company
#TODO PUT /companies/:id # update a specific company
#TODO DELETE /companies/:id #remove a specific company

#TODO GET /departments # get all departments
#TODO GET /departments/:id # get departments with id :id
#TODO POST /departments  # Add new department
#TODO PUT /departments/:id # update a specific department
#TODO DELETE /departments/:id #remove a specific departments

#DONE GET /personality_types # get all personality types
#DONE GET /personality_types/:signature #get personality type with signature

#DONE GET /letters # get all letters
#DONE GET /letters/:letter #get specific letter
